name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: thanhtunguet/wbs-api:latest # Set the default tag here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

      - name: Tag Docker image
        run: docker tag ${{ env.DOCKER_IMAGE_TAG }} ${{ env.DOCKER_IMAGE_TAG }}

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE_TAG }}
